NGStoolsDB/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name = 'about_page'),
    path('articles/', include('articles.urls')),
    path('accounts/', include("accounts.urls")),
    path('', views.articles_list, name="home")
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =  [
    path('singup/', views.singup_view, name='singup_form'),
    path('login/', views.login_view, name='login_form'),
    path('logout/',views.logout_view, name = 'logout')
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns =  [
    path('', views.articles_list, name = 'articles_list'),
    path('<slug:slug>/', views.articale_detail, name='detail')  # This MUST me last url
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Articles(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    type = models.CharField(max_length=100, default="general")
    date = models.DateTimeField(auto_now_add=True)
    link = models.URLField(max_length=500,blank=True, default="#")
    thumb = models.ImageField(default="default.png", blank=True)


    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Articles,on_delete=models.CASCADE,related_name='comments')
    name = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

articles/forms.py
from .models import Comment
from django import forms


from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

def singup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            print("****valid")
            form.save()
            return redirect('articles:articles_list')
        else:
            #TODO add here case it is not valid notification
            print("***not")
            form = UserCreationForm()
            return render(request, 'accounts/singup.html', {'form': form})

    else:
        form = UserCreationForm()
        return render(request, 'accounts/singup.html', {'form' : form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:articles_list')
    else:
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('articles:articles_list')

articles/views.py
from django.shortcuts import render
from .models import Articles
from django.http import HttpResponse
from .models import Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'index.html')

def articles_list(request):
    #articles = Articles.objects.all().order_by('date')
    articles_alignment = Articles.objects.all().filter(type = "alignment")
    articles_DE = Articles.objects.all().filter(type="DE")
    articles_counts = Articles.objects.all().filter(type="count_reads")
    articles_qc = Articles.objects.all().filter(type="QC")
    articles_func = Articles.objects.all().filter(type="functional")
    return render(request,"articles/articles_list.html",
                  {"articles_alignment":articles_alignment,
                   "articles_DE":articles_DE,
                   "articles_counts":articles_counts,
                   "articles_qc" : articles_qc,
                   "articles_func":articles_func})


def articale_detail(request, slug):
    article = Articles.objects.get(slug=slug)
    comments = article.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.article = article
            new_comment.name = request.user
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    #return render(request, "articles/article_detail.html", {"article": article})
    return render(request, "articles/article_detail.html", {'article': article,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

def about(request):
    return render(request,'about.html')

templates/about.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>About me</h1>
<p>
    I am a bioinformatician, NGS expert.
    <br>Examples for my work can be found <a href="https://bioinfodata.github.io/BioInfoData-Portfolio/">here</a>.
    <br>For more information please <a href="mailto:reut.fluss@gmail.com">contact me</a>.
</p>
{% endblock %}

templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login_form' %}" method="post">
    {% csrf_token %}
    <p>
        {{ form }}
    </p>

    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <div class="singup">
        <p>
        <button type="submit" value="Submit"  > Login </button>
        </p>
    </div>
</form>
{% endblock %}

templates/accounts/singup.html
{% extends 'base_layout.html' %}
{% load widget_tweaks %}
{% block content %}
<h1>Singup</h1>

    <form class="site-form" action="{% url 'accounts:singup_form' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <p>Username:
        {% render_field form.username type="text" class="form-control" id="exampleInputUsername" placeholder="Username" %}
        </p>
    </div>

    <div class="form-group">
        <p>
        Password: {% render_field form.password1 type="password" class="form-control" id="exampleInputPassword" placeholder="Password" %}
        </p>
    </div>

    <div class="form-group">
        <p>
        Confirm Password: {% render_field form.password2 type="password" class="form-control" id="exampleInputPassword1" placeholder="Confirm Password" %}
        </p>
    </div>

    <div class="singup">
        <p>
        <button type="submit" value="Submit"  > Register </button>
        </p>
    </div>

</form>


{% endblock %}

templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="article-detail">
    <div class="article">
        <h1>{{article.title}}</h1>
        <p>{{article.body}}</p>
        <p style="font-size: large;">Last update at {{article.date}}</p>
        <a href = "{{article.link}}"  target="_blank" >
            Go to {{article.title}} site
        </a>


    </div>
</div>

<div class="add_comment">
{% if new_comment %}
        <div class="alert alert-success" role="alert">
          <p> Thank you! Your comment was submitted</p>
        </div>
{% else %}

    {% if user.is_authenticated %}
        {% load crispy_forms_tags %}
        <p><strong>Add your comment here:</strong></p>
        <form method="post" style="margin-top: 1.3em;">
              {% render_field comment_form.body type="text" class="form-control" id="comment" placeholder="Add comment" %}
              {% csrf_token %}
              <p style="margin-left: 50px;"><button type="submit" class="btn btn-primary btn-lg">Submit</button></p>
        </form>

    {% else %}
        <p>To add a comment please <a href="{% url 'accounts:login_form' %}">Login</a></p>
    {% endif %}
{% endif %}
</div>



{% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p><strong>{{ comment.name }}</strong></p>
            <p>{{ comment.created_on }}</p>
            <p>{{ comment.body | linebreaks }}</p>

        </div>
        {% endfor %}

{% endblock %}

templates/articles/articles_list.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>NGS Tools For Beginners</h1>
<p class ="intro">
    This website summarizes the most useful tools for bioinformatic analysis of
</p>
<p><strong>Next Generation Sequencing (NGS)</strong></p>
<p class ="intro">
    If you want to leave a comment on the articles please <a href="{% url 'accounts:login_form' %}">Login</a>
    or
    <a href="{% url 'accounts:singup_form' %}">Signup</a>
</p>

<div class="types">
<nav>
    <ul>
        <li><a href="#func">Functional analysis</a> </li>
        <li><a href="#DE">Differential Expression</a> </li>
        <li><a href="#counts">Reads count</a></li>
        <li><a href="#alignment">Alignment Tools</a></li>
        <li><a href="#qc">Sequencing QC</a></li>

    </ul>

</nav>


</div>

<h2 id="qc">Sequencing QC</h2>
<div class="articles">
    {%for article in articles_qc %}
    <div class="article">
        <a href ="{% url 'articles:detail' slug=article.slug %}">
            {{article.title}}
        </a>
    </div>
    {%endfor%}
</div>

<h2 id = "alignment">Alignment Tools</h2>
<div class="articles">
    {%for article in articles_alignment %}
    <div class="article">
        <a href ="{% url 'articles:detail' slug=article.slug %}">
            {{article.title}}
        </a>
    </div>
    {%endfor%}
</div>


<h2 id="counts">Read Counts</h2>
<div class="articles">
    {%for article in articles_counts %}
    <div class="article">
        <a href ="{% url 'articles:detail' slug=article.slug %}">
            {{article.title}}
        </a>
    </div>
    {%endfor%}
</div>

<h2 id="DE">Differential Expression</h2>
<div class="articles">
    {%for article in articles_DE %}
    <div class="article">
        <a href ="{% url 'articles:detail' slug=article.slug %}">
            {{article.title}}
        </a>
    </div>
    {%endfor%}
</div>


<h2 id ="func">Functional analysis</h2>
<div class="articles">
    {%for article in articles_func %}
    <div class="article">
        <a href ="{% url 'articles:detail' slug=article.slug %}">
            {{article.title}}
        </a>
    </div>
    {%endfor%}
</div>

{% endblock %}

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>atricles</title>
    <link rel="stylesheet" href="{% static 'mystyle2.css' %}">
</head>
<body>
    <div class="wrapper">
        <h1><a href="{% url 'articles:articles_list' %}" >
            <img  width="100%", height="10%" src="{% static 'genetics-bioinformatics.jpg' %}">
        </a></h1>
        <nav>
            <ul>
                <li><a href="{% url 'articles:articles_list' %}">Home</a></li>
                <li><a href="{% url 'about_page' %}">About me</a></li>
            {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href ="#">Hello {{user}}</a></li>
                 {% else %}
                <li><a href="{% url 'accounts:login_form' %}">Login</a></li>
                <li><a href="{% url 'accounts:singup_form' %}">Signup</a></li>

            {% endif %}
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>